### PR TITLE
Update App.tsx - reference chat name in url hash #515

### PR DESCRIPTION
**Pull request by 7flash**

### CODE REVIEW

**Comment by zewebdev1337** [comment]
just a headsup, there's an issue with "chatIndexToSet': after merging into my fork the build process fails with:
```
src/App.tsx(56,11): error TS2304: Cannot find name 'chatIndexToSet'.
src/App.tsx(58,31): error TS2304: Cannot find name 'chatIndexToSet'.
src/App.tsx(58,55): error TS2304: Cannot find name 'chatIndexToSet'.
src/App.tsx(68,16): error TS2304: Cannot find name 'chatsFromStore'.
src/App.tsx(68,34): error TS2304: Cannot find name 'chatsFromStore'.
src/App.tsx(69,7): error TS2304: Cannot find name 'chatIndexToSet'.
src/App.tsx(69,60): error TS2304: Cannot find name 'chatsFromStore'.
src/App.tsx(70,11): error TS2304: Cannot find name 'chatIndexToSet'.
src/App.tsx(71,29): error TS2304: Cannot find name 'chatIndexToSet'.
error Command failed with exit code 2.
```

I didn't check the code as I'm currently only merging PRs into my fork, if I fix it, which seems like an easy fix, I'll share the fix back
